name: Nuxt.js Front-End CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: generate static project
      run: yarn generate     
