name: Deploy the frontend container 

on:
  push:    
    tags:     # Only run when a new tag is pushed to the repository
      - 'v*'  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:       
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
                      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:          
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
        
      - name: Get the version
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:          
          context: .
          file: ./docker/Dockerfile
          registry: ${{ env.REGISTRY }}
          push: true          
          tags: nextmasjiddocker/nextmasjid-frontend:${{ steps.tag.outputs.VERSION }}, nextmasjiddocker/nextmasjid-frontend:latest  

      #- name: Install SSH Key
      #  uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
      #  with:
      #    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #    ssh-host: ${{ secrets.SERVER }}    
          
            
          
